-- Clink macros generated from PowerShell profile aliases and functions
-- (Ensure GIT_MAIN_BRANCH and GIT_DEVELOP_BRANCH env vars are set to your main/develop branch names)
clink.print("Loading aliases...")
-- Directory listing aliases (using the 'nicels' tool for enhanced ls output)
os.setalias("ls", "nls -aA --sd $*")         -- corresponds to `lls` function:contentReference[oaicite:5]{index=5}
os.setalias("tree", "nls -laA --gs --sd --tree $*")
--os.setalias("tree", "nls -lah --sd --tree $*")
os.setalias("ll", "nls -laA --sd --gs --df --header --report $*")
os.setalias("la", "nls -laA --sd --gs --report --header -1 $*")
os.setalias("l", "nls --sd $*")

-- Git command aliases (shortcuts for common Git operations)
os.setalias("ga", "git add $*")
os.setalias("gaa", "git add --all $*")
os.setalias("gam", "git am $*")
os.setalias("gama", "git am --abort $*")
os.setalias("gamc", "git am --continue $*")
os.setalias("gams", "git am --skip $*")
os.setalias("gamscp", "git am --show-current-patch $*")
os.setalias("gap", "git apply $*")
os.setalias("gapa", "git add --patch $*")
os.setalias("gapt", "git apply --3way $*")
os.setalias("gau", "git add --update $*")
os.setalias("gav", "git add --verbose $*")
os.setalias("gb", "git branch $*")
os.setalias("gbD", "git branch --delete --force $*")
os.setalias("gba", "git branch -a $*")
os.setalias("gbd", "git branch -d $*")
-- os.setalias("gbda", "powershell -NoProfile -Command \"git branch --no-color --merged | Select-String -NotMatch \\\"^([+*]|\\s*($env:GIT_MAIN_BRANCH|$env:GIT_DEVELOP_BRANCH))\\s*$\\\" | ForEach-Object { git branch --delete $_ }\"")  -- deletes merged branches except main/dev:contentReference[oaicite:6]{index=6}
os.setalias("gbg", 'git branch -vv | findstr /C:": gone]"')
os.setalias("gbgD", 'for /F "tokens=1" %b in (\'git branch -vv ^| findstr /C:": gone]"\') do git branch -D %b')
os.setalias("gbgd", 'for /F "tokens=1" %b in (\'git branch -vv ^| findstr /C:": gone]"\') do git branch -d %b')
os.setalias("gbl", "git blame -b -w $*")
os.setalias("gbm", "git branch --move $*")
os.setalias("gbnm", "git branch --no-merged $*")
os.setalias("gbr", "git branch --remote $*")
os.setalias("gbs", "git bisect $*")
os.setalias("gbsb", "git bisect bad $*")
os.setalias("gbsc", "git branch --show-current $*")
os.setalias("gbsg", "git bisect good $*")
os.setalias("gbsn", "git bisect new $*")
os.setalias("gbso", "git bisect old $*")
os.setalias("gbsr", "git bisect reset $*")
os.setalias("gbss", "git bisect start $*")
os.setalias("gc", "git commit --verbose $*")
os.setalias("gc!", "git commit --verbose --amend $*")
os.setalias("gca", "git commit --verbose --all $*")
os.setalias("gca!", "git commit --verbose --all --amend $*")
os.setalias("gcam", "git commit --all --message $*")
os.setalias("gcan!", "git commit --verbose --all --no-edit --amend $*")
os.setalias("gcans!", "git commit --verbose --all --signoff --no-edit --amend $*")
os.setalias("gcas", "git commit --all --signoff $*")
os.setalias("gcasm", "git commit --all --signoff --message $*")
os.setalias("gcb", "git checkout -b $*")
os.setalias("gcd", "git checkout %GIT_DEVELOP_BRANCH%")
os.setalias("gcf", "git config --list $*")
os.setalias("gcl", "git clone --recursive $*")
os.setalias("gclean", "git clean -fd $*")
os.setalias("gcm", "git checkout %GIT_MAIN_BRANCH%")
os.setalias("gcmsg", "git commit --message $*")
os.setalias("gcn!", "git commit --verbose --no-edit --amend $*")
os.setalias("gco", "git checkout $*")
os.setalias("gcor", "git checkout --recurse-submodules $*")
os.setalias("gcount", "git shortlog --summary --numbered $*")
os.setalias("gcp", "git cherry-pick $*")
os.setalias("gcpa", "git cherry-pick --abort $*")
os.setalias("gcpc", "git cherry-pick --continue $*")
os.setalias("gcps", "git cherry-pick -s $*")
os.setalias("gcs", "git commit --gpg-sign $*")
os.setalias("gcsm", "git commit --signoff --message $*")
os.setalias("gcss", "git commit --gpg-sign --signoff $*")
os.setalias("gcssm", "git commit --gpg-sign --signoff --message $*")
os.setalias("gd", "git diff $*")
os.setalias("gdca", "git diff --cached $*")
os.setalias("gdct", 'for /F %h in (\'git rev-list --tags --max-count=1\') do @git describe --tags %h')
os.setalias("gdcw", "git diff --cached --word-diff $*")
os.setalias("gds", "git diff --staged $*")
os.setalias("gdt", "git diff-tree --no-commit-id --name-only -r $*")
os.setalias("gdtool", "git difftool -d $*")
os.setalias("gdup", "git diff \"@{upstream}\" $*")
os.setalias("gdw", "git diff --word-diff $*")
os.setalias("gf", "git fetch $*")
os.setalias("gfa", "git fetch --all --prune $*")
os.setalias("gfg", 'git ls-files | findstr /I /C:"%*"')
os.setalias("gfo", "git fetch origin $*")
os.setalias("gg", "git gui citool $*")
os.setalias("gga", "git gui citool --amend $*")
os.setalias("ggpull", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git pull origin %b')
os.setalias("ggpush", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git push origin %b')
os.setalias("ggsup", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git branch --set-upstream-to=origin/%b')
os.setalias("ghh", "git help $*")
os.setalias("gignore", "git update-index --assume-unchanged $*")
os.setalias("gignored", 'git ls-files -v | findstr /R "^[a-z]"')
os.setalias("git-svn-dcommit-push", "git svn dcommit$Tgit push github %GIT_MAIN_BRANCH%:svntrunk")  -- runs two commands:contentReference[oaicite:7]{index=7}
os.setalias("gk", "gitk --all --branches $*")
os.setalias("gke", "gitk --all")
os.setalias("gl", "git pull $*")
os.setalias("glg", "git log --stat $*")
os.setalias("glgg", "git log --graph $*")
os.setalias("glgga", "git log --graph --decorate --all $*")
os.setalias("glgm", "git log --graph --max-count=10 $*")
os.setalias("glgp", "git log --stat -p $*")
os.setalias("glo", "git log --oneline --decorate $*")
os.setalias("glod", 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"')
os.setalias("glods", 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short')
os.setalias("glog", "git log --oneline --decorate --graph $*")
os.setalias("gloga", "git log --oneline --decorate --graph --all $*")
os.setalias("glol", 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"')
os.setalias("glola", 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --all')
os.setalias("glols", 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat')
os.setalias("gluc", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git pull upstream %b')
os.setalias("glum", "git pull upstream %GIT_MAIN_BRANCH%")
os.setalias("gm", "git merge $*")
os.setalias("gma", "git merge --abort $*")
os.setalias("gmom", "git merge origin/%GIT_MAIN_BRANCH%")
os.setalias("gms", "git merge --squash $*")
os.setalias("gmt", "git mergetool --no-prompt $*")
os.setalias("gmtl", "git mergetool --no-prompt $*")
os.setalias("gmtlvim", "git mergetool --no-prompt --tool=vimdiff $*")
os.setalias("gmtvim", "git mergetool --no-prompt --tool=vimdiff $*")
os.setalias("gmum", "git merge upstream/%GIT_MAIN_BRANCH%")
os.setalias("gp", "git push $*")
os.setalias("gpd", "git push --dry-run $*")
os.setalias("gpf", "git push --force-with-lease $*")
os.setalias("gpf!", "git push --force $*")
os.setalias("gpoat", "git push origin --all$Tgit push origin --tags")
os.setalias("gpod", "git push origin --delete $*")
os.setalias("gpr", "git pull --rebase $*")
os.setalias("gpristine", "git reset --hard$Tgit clean --force -dfx")
os.setalias("gpsup", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git push --set-upstream origin %b')
os.setalias("gpsupf", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git push --set-upstream origin %b --force-with-lease')
os.setalias("gpu", "git push upstream $*")
os.setalias("gpv", "git push --verbose $*")
os.setalias("gr", "git remote $*")
os.setalias("gra", "git remote add $*")
os.setalias("grb", "git rebase $*")
os.setalias("grba", "git rebase --abort $*")
os.setalias("grbc", "git rebase --continue $*")
os.setalias("grbd", "git rebase %GIT_DEVELOP_BRANCH%")
os.setalias("grbi", "git rebase --interactive $*")
os.setalias("grbm", "git rebase %GIT_MAIN_BRANCH%")
os.setalias("grbo", "git rebase --onto $*")
os.setalias("grbom", "git rebase origin/%GIT_MAIN_BRANCH%")
os.setalias("grbs", "git rebase --skip $*")
os.setalias("grep", 'powershell -NoProfile -Command "Get-ChildItem -Recurse -Exclude \'.bzr\',\'CVS\',\'.git\',\'.hg\',\'.svn\' | Select-String $*"')
os.setalias("grev", "git revert $*")
os.setalias("grh", "git reset $*")
os.setalias("grhh", "git reset --hard $*")
os.setalias("grhk", "git reset --keep $*")
os.setalias("grhs", "git reset --soft $*")
os.setalias("grm", "git rm $*")
os.setalias("grmc", "git rm --cached $*")
os.setalias("grmv", "git remote rename $*")
os.setalias("groh", 'for /F %b in (\'git rev-parse --abbrev-ref HEAD\') do @git reset origin/%b --hard')
os.setalias("grrm", "git remote remove $*")
os.setalias("grs", "git restore $*")
os.setalias("grset", "git remote set-url $*")
os.setalias("grss", "git restore --source $*")
os.setalias("grst", "git restore --staged $*")
os.setalias("grt", 'for /F "delims=" %d in (\'git rev-parse --show-toplevel\') do @pushd "%d"')
os.setalias("gru", "git reset -- $*")
os.setalias("grup", "git remote update $*")
os.setalias("grv", "git remote --verbose $*")
os.setalias("gsb", "git status --short --branch $*")
os.setalias("gsd", "git svn dcommit $*")
os.setalias("gsh", "git show $*")
os.setalias("gsi", "git submodule init $*")
os.setalias("gsps", "git show --pretty=short --show-signature $*")
os.setalias("gsr", "git svn rebase $*")
os.setalias("gss", "git status --short $*")
os.setalias("gst", "git status $*")
os.setalias("gsta", "git stash save $*")
os.setalias("gstaa", "git stash apply $*")
os.setalias("gstall", "git stash --all $*")
os.setalias("gstc", "git stash clear $*")
os.setalias("gstd", "git stash drop $*")
os.setalias("gstl", "git stash list $*")
os.setalias("gstp", "git stash pop $*")
os.setalias("gsts", "git stash show $*")
os.setalias("gsu", "git submodule update $*")
os.setalias("gsw", "git switch $*")
os.setalias("gswc", "git switch --create $*")
os.setalias("gswd", "git switch %GIT_DEVELOP_BRANCH%")
os.setalias("gswm", "git switch %GIT_MAIN_BRANCH%")
os.setalias("gta", "git tag --annotate $*")
os.setalias("gts", "git tag --sign $*")
os.setalias("gtv", "git tag $* | sort")
os.setalias("gunignore", "git update-index --no-assume-unchanged $*")
os.setalias("gunwip", "git reset HEAD~1 $*")
os.setalias("gup", "git pull --rebase $*")
os.setalias("gupa", "git pull --rebase --autostash $*")
os.setalias("gupav", "git pull --rebase --autostash --verbose $*")
os.setalias("gupom", "git pull --rebase origin %GIT_MAIN_BRANCH%")
os.setalias("gupomi", "git pull --rebase=interactive origin %GIT_MAIN_BRANCH%")
os.setalias("gupv", "git pull --rebase --verbose $*")
os.setalias("gwch", "git whatchanged -p --abbrev-commit --pretty=medium $*")
os.setalias("gwip", 'git add -A$Tgit commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"')
os.setalias("gwt", "git worktree $*")
os.setalias("gwta", "git worktree add $*")
os.setalias("gwtls", "git worktree list $*")
os.setalias("gwtmv", "git worktree move $*")
os.setalias("gwtrm", "git worktree remove $*")

-- Miscellaneous aliases and utility functions
-- os.setalias("pwshconfig", 'notepad "%USERPROFILE%\\Documents\\PowerShell\\Profile.ps1"')  -- opens PowerShell all-hosts profile:contentReference[oaicite:8]{index=8}
-- os.setalias("osrelease", 'powershell -NoProfile -Command "Get-ComputerInfo -Property CsName,OsName,OsVersion,OsBuildNumber,WindowsBuildLabEx,OsManufacturer,OsSerialNumber,CsProcessors,CsNetworkAdapters,OsMuiLanguages | Format-List"')  -- shows system info:contentReference[oaicite:9]{index=9}
os.setalias("pwd", "cd")  -- prints current directory (alias for Get-CurrentPath):contentReference[oaicite:10]{index=10}
-- os.setalias("file", 'powershell -NoProfile -Command "$shell = New-Object -ComObject Shell.Application; $folder = $shell.Namespace((Split-Path \'%*\' -Parent)); if($folder) { $file = $folder.ParseName((Split-Path \'%*\' -Leaf)); if($file) { $i=0; while($folder.GetDetailsOf($folder.Items(), $i) -ne \'Perceived type\' -and $i -lt 266) {$i++}; if($i -lt 266) { $t = $folder.GetDetailsOf($file, $i); if($t) { Write-Host $t } else { Write-Host \'No perceived type\' } } else { Write-Host \'Perceived type not found\' } } else { Write-Host \'Error: file not found\' } }"')  -- gets file's "Perceived type" via Shell COM:contentReference[oaicite:11]{index=11}:contentReference[oaicite:12]{index=12}
os.setalias("which", "where $*")            -- finds first occurrence in PATH (similar to *Get-Command Source*):contentReference[oaicite:13]{index=13}
os.setalias("whereis", "echo All available paths for '$1':$Twhere $1")  -- lists all occurrences in PATH:contentReference[oaicite:14]{index=14}
os.setalias("sudo", "gsudo $*")             -- elevate command (requires gsudo utility)
